config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  resources :friends
  get 'home/about'
  #root 'home#index'
  root 'friends#index'
 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ckeditor/asset.rb
# frozen_string_literal: true

class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
# frozen_string_literal: true

class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
# frozen_string_literal: true

class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :friends




         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!,except: [:index, :show]
  before_action :current_user, only: [:edit, :update, :destroy]

 
  def index
    @friends = Friend.all
  end

 
  def show
    
  end

  
  def new
    #@friend = Friend.new
    @friend = current_user.friends.build
  end

  
  def edit
  end

  
  def create
    #@friend = Friend.new(friend_params)
    @friend =current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Autherized to Edit This Friend" if @friend.nil?
  end 


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :password, :instagram, :facebook, :favourite, :birth_date, :user_id, :description, :image, :avatar)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
 
  end

  def about
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <% form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name, class:"form-control", placeholder:"first_name" %>
  </div>

  <div class="field form-group">
    <%  form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name, class:"form-control", placeholder:"last_name" %>
  </div>

  <div class="field form-group">
    <%  form.label :email, style: "display: block" %>
    <%= form.text_field :email, class:"form-control", placeholder:"email" %>
  </div>

  <div class="field form-group">
    <%  form.label :phone, style: "display: block" %>
    <%= form.text_field :phone, class:"form-control", placeholder:"phone" %>
  </div>

  <div class="field form-group">
    <%  form.label :twitter, style: "display: block" %>
    <%= form.text_field :twitter, class:"form-control" , placeholder:"twitter" %>
  </div>

  <div class="field form-group">
    <%  form.label :password, style: "display: block" %>
    <%= form.text_field :password, class:"form-control", placeholder:"passward" %>
  </div>

  <div class="field form-group">
    <%  form.label :instagram, style: "display: block" %>
    <%= form.text_field :instagram, class:"form-control", placeholder:"instagram" %>
  </div>

  <div class="field form-group">
    <%  form.label :facebook, style: "display: block" %>
    <%= form.text_field :facebook, class:"form-control", placeholder:"facebook" %>
  </div>

  <div class="field form-group">
    <%  form.label :favourite, style: "display: block" %>
    <%= form.text_field :favourite, class:"form-control", placeholder:"favourite" %>
  </div>

  <div class="field form-group">
    <%  form.label :birth_date, style: "display: block", placeholder:"birth_date"  %>
    <%= form.date_field :birth_date, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%  form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value:current_user.id, type: :hidden %>
  </div>

  <div class="field form-group">
    <%  form.label :description, style: "display: block" %>
    <%= form.text_area :description, class:"form-control", placeholder:"description" %>
  </div>


  <br/>
  <div>
    <%= form.submit class:'btn btn-secondary' %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
<% if user_signed_in? %>
<h1>Friends List</h1>

  <table class="table table-striped table-bordered table-hover">
     <thead class="thead-dark">
            <tr>
              <th>Name </th>
              <th>Email</th>
              <th>phone</th>
              <th>Twiter</th>
              <th>Password</th>
              <th>Instagram</th>
              <th>Facebook</th>
              <th>Favourite</th>
              <th>Birth date </th>
              <th>User Id </th>
              <th>Description</th>
              <th></th>
            </tr>
    </thead>
    <tbody>
        <% @friends.each do |friend| %>

        <!-- so only the friends that are associated to that user show -->
        <% if friend.user == current_user %>
          <tr>
            <td>
              <!-- <%= link_to 'Show', friend %> -->
              <!-- <%= friend.first_name %> -->
              <!-- <%= friend.last_name %> -->
              <%= link_to friend.first_name + ' ' + friend.last_name, friend %>
            </td>
            <td><%= friend.email %></td>  
            <td><%= friend.phone %></td>
            <td><%= friend.twitter %></td>
            <td><%= friend.password %></td>
            <td><%= friend.instagram %></td>
            <td><%= friend.facebook %></td>
            <td><%= friend.favourite %></td>
            <td><%= friend.birth_date %></td>
            <td><%= friend.user_id %></td>
            <td><%= friend.description %></td>
            
            
            <!-- <td><%= link_to 'Show', friend %></td> -->
            <!-- % if friend.user == current_user % -->
            <!-- <td><%= link_to 'Edit', edit_friend_path(friend) %></td> -->
            <td><%= link_to 'Delete', friend, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm"%></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
<br>
  
<%= link_to 'New Friend', new_friend_path, class:"btn btn-light" %>

<br>

<% else %>

<div class="header">
  <h2></h2>
</div>

<% end %>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<%= link_to 'Show', @friend, class:"btn btn-dark" %>

<%= link_to 'Delete', @friend, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger"%>

<%= link_to 'Back', friends_path, class:"btn btn-secondary" %>

app/views/friends/index.html.erb
<p style="color: green"><%= notice %></p>


<div  id="friends ">
  <% @friends.each do |friend| %>
    <%= render friend %>
    
    <p>
      <%= link_to "Friends", friend, class:"btn btn-secondary"%>
    </p>
    <br/>
  <% end %>
</div>

<br/>

<%= link_to "New friend", new_friend_path, class:"btn btn-dark" %>
  

app/views/friends/new.html.erb
<h1>Add New Friend</h1>
<br/> 

<%= render 'form', friend: @friend %>

<br/> 

<%= link_to 'Back', friends_path, class:"btn btn-secondary" %>

app/views/friends/show.html.erb
<p style="color: green"><%= notice %></p>



<div class="bg-light p-5">
  <h1 class="display-4">
    <%= @friend.first_name %>
    <%= @friend.last_name %>
  </h1>
  
  <p class="lead">
    <%= @friend.email %> | <%= @friend.phone %> | <%= @friend.twitter %> |

    <%= @friend.favourite %> | <%= @friend.facebook %> | <%= @friend.birth_date %> | 
  </p>
  
   <div>
    <p class="lead">
      <%= @friend.description %> 
  </p>
  </div>

  

  <br/>
  <!-- to create a line: <hr class="my-4"> -->
  
  <%= link_to 'Edit', edit_friend_path(@friend), class:"btn btn-dark" %> <!-- to add something to the screen you dont need special structure like <>, you could just put: | , (or any other text) in between these two lines and it will show on screen -->

  <%= link_to 'Delete', @friend, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger"%>
  
  <%= link_to 'Back', friends_path, class:"btn btn-secondary" %>
</div>

app/views/home/_header.html.erb
<!-- header parcial file, you use the _ at the beginning so rails knows to treat it as a parcial -->
<!-- we can access this parcial and it will spit out onto the page whereever we put it -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark"> <!--navbar-light bg-light -->
  <div class="container-fluid">
  	<!-- replace the old link to use ruby-->
  	<!-- <a class="navbar-brand" href="#">Friend App</a> -->
  	<%= link_to 'Friend App', root_path, class:"navbar-brand"%>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">

          <%= link_to 'About Us', home_about_path, class:"nav-link"%>
          <!-- the html file is in home, with the name about, and we always put path -->
        </li>
      	<!-- only if user signed in -->
        <% if  user_signed_in? %>
	        <li class="nav-item">
	          <%= link_to 'Add Friend', new_friend_path, class:"nav-link"%>
	        </li>
        	<li class="nav-item">
          		<%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link"%>
        	</li>
        	<li class="nav-item">
          		<%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link"%>
        	</li>

        <!-- if user not signed in -->
        <% else %>
	        <li class="nav-item">
	          <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link"%>
	        </li>

	        <li class="nav-item">
	          <%= link_to 'Log In', new_user_session_path, class:"nav-link"%>
	        </li>
	    <% end %>
        
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us...</h1>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
  box-sizing: border-box;
}

/* Add a gray background color with some padding */
body {
  font-family: Arial;
  padding: 20px;
  background: ##fff;
}

/* Header/Blog Title */
.header {
  padding: 30px;
  font-size: 40px;
  text-align: center;
  background: white;
}

/* Create two unequal columns that floats next to each other */
/* Left column */
.leftcolumn {   
  float: left;
  width: 75%;
}

/* Right column */
.rightcolumn {
  float: left;
  width: 25%;
  padding-left: 20px;
}

/* Fake image */
.fakeimg {
  background-color: #aaa;
  width: 100%;
  padding: 20px;
}

/* Add a card effect for articles */
.card {
   background-color: white;
   padding: 20px;
   margin-top: 20px;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Footer */
.footer {
  padding: 20px;
  text-align: center;
  background: #ddd;
  margin-top: 20px;
}

/* Responsive layout - when the screen is less than 800px wide, make the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 800px) {
  .leftcolumn, .rightcolumn {   
    width: 100%;
    padding: 0;
  }
}
</style>
</head>
<body>

<div class="header">
  <h2>Friends List</h2>
</div>

<div class="row">
  <div class="leftcolumn">
    <div class="card">
      <h2>TITLE HEADING</h2>
      <h5>Title description, Dec 7, 2017</h5>
      <div class="fakeimg" style="height:200px;">Image</div>
      <p>Some text..</p>
      <p>Sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
    </div>
    <div class="card">
      <h2>TITLE HEADING</h2>
      <h5>Title description, Sep 2, 2017</h5>
      <div class="fakeimg" style="height:200px;">Image</div>
      <p>Some text..</p>
      <p>Sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
    </div>
  </div>
  <div class="rightcolumn">
    <div class="card">
      <h2>About Me</h2>
      <div class="fakeimg" style="height:100px;">Image</div>
      <p>Some text about me in culpa qui officia deserunt mollit anim..</p>
    </div>
    <div class="card">
      <h3>Popular Post</h3>
      <div class="fakeimg">Image</div><br>
      <div class="fakeimg">Image</div><br>
      <div class="fakeimg">Image</div>
    </div>
    <div class="card">
      <h3>Follow Me</h3>
      <p>Some text..</p>
    </div>
  </div>
</div>

<div class="footer">
  <h2>Footer</h2>
</div>

</body>
</html>























        
       
    

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Friends App</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%=render "home/header" %>
    <div class = "container">
      <br/>
      
        <%= yield %>

      
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>